### ISSUE TITLE
Driver creates duplicate ids and causes weird line breaks.

### ISSUE THREAD

**Issue by Themanwithoutaplan** [jgoguen/calibre-kobo-driver#101]
I hope I've got the right plugin. I'm using 3.2.7 with my Kobo Aura One and I've recently found it causing problems with line breaks occurring randomly. Comparing the source file with generated version and it looks like it is excessively greedy and verbose.

The original line one book looks like this:
`<h2 class="h2"><a id="ch01"/><a id="page_9"/>1<br/>Sammy</h2>`
After processing this becomes:
`<h2 class="h2"><a id="ch01"></a><a id="page_9"></a><span class="koboSpan" id="kobo.3.1">1</span><br/><span class="koboSpan" id="kobo.5.1">Sammy</span></h2>`

I don't think the spans are necessary but it's later that there are real problems:

`<a id="page_10"></a></p><a id="page_10"><span class="koboSpan" id="kobo.14.1">`
Not only is the id repeated but because the second anchor isn't directly closed, it can cause problems if the same id crosses paragraph or page boundaries.

The original:
`Tilyou had lived on Surf Avenue in his <a id="page_11"/>own private house,`

becomes.

```
n his</span></a> <a id="page_11"></a>
        </p><a id="page_11"><span class="koboSpan" id="kobo.19.1">own private house,
```
Which has a line break after "his".

**Comment by jgoguen** [comment]
You're running an outdated version. If you can reproduce this in v3.2.10 (just published, so calibre may need a couple hours to offer it or you can manually install the packages I published on Github) please re-open this.
