### ISSUE TITLE
kepup output error

### ISSUE THREAD

**Issue by agrande985** [jgoguen/calibre-kobo-driver#104]
calibre, version 4.18.0 (win32, embedded-python: True)

D:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Conversion options changed from defaults:
  output_profile: u'generic_eink'
  read_metadata_from_opf: u'C:\\Users\\ken\\AppData\\Local\\Temp\\calibre_061ctg\\2lmty7.opf'
  verbose: 2
  cover: u'C:\\Users\\ken\\AppData\\Local\\Temp\\calibre_061ctg\\lnpjos.jpeg'
Resolved conversion options
calibre version: 4.18.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\ken\\AppData\\Local\\Temp\\calibre_061ctg\\lnpjos.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000000045D5A88>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'kepub_clean_markup': True,
 'kepub_disable_hyphenation': False,
 'kepub_hyphenate': True,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000000045DB6C8>,
 'page_breaks_before': u'/',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\ken\\AppData\\Local\\Temp\\calibre_061ctg\\2lmty7.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: EPUB Input running
on C:\Users\ken\AppData\Local\Temp\calibre_061ctg\pauhni.epub
Found HTML cover titlepage.xhtml
Parsing all content...
Parsing index_split_088.html ...
Parsing index_split_021.html ...
Parsing index_split_132.html ...
Parsing index_split_059.html ...
Parsing index_split_000.html ...
Parsing index_split_003.html ...
Parsing index_split_061.html ...
Parsing index_split_063.html ...
Parsing index_split_136.html ...
Parsing index_split_114.html ...
Parsing index_split_065.html ...
Parsing index_split_099.html ...
Parsing index_split_019.html ...
Parsing index_split_067.html ...
Parsing index_split_121.html ...
Parsing stylesheet.css ...
Parsing index_split_122.html ...
Parsing index_split_116.html ...
Parsing index_split_071.html ...
Parsing index_split_123.html ...
Parsing index_split_039.html ...
Parsing index_split_073.html ...
Parsing index_split_124.html ...
Parsing index_split_075.html ...
Parsing index_split_125.html ...
Parsing index_split_118.html ...
Parsing index_split_077.html ...
Parsing index_split_127.html ...
Parsing index_split_107.html ...
Parsing index_split_079.html ...
Parsing index_split_128.html ...
Parsing index_split_141.html ...
Parsing index_split_015.html ...
Parsing index_split_117.html ...
Parsing index_split_129.html ...
Parsing index_split_120.html ...
Parsing index_split_083.html ...
Parsing index_split_130.html ...
Parsing index_split_069.html ...
Parsing index_split_131.html ...
Parsing index_split_142.html ...
Parsing index_split_095.html ...
Parsing index_split_133.html ...
Parsing index_split_006.html ...
Parsing index_split_139.html ...
Parsing index_split_007.html ...
Parsing index_split_096.html ...
Parsing index_split_008.html ...
Parsing index_split_137.html ...
Parsing index_split_009.html ...
Parsing index_split_046.html ...
Parsing index_split_010.html ...
Parsing index_split_143.html ...
Parsing index_split_100.html ...
Parsing index_split_013.html ...
Parsing index_split_085.html ...
Parsing index_split_011.html ...
Parsing index_split_012.html ...
Parsing index_split_005.html ...
Parsing index_split_094.html ...
Parsing index_split_040.html ...
Parsing index_split_104.html ...
Parsing index_split_042.html ...
Parsing page_styles.css ...
Parsing index_split_112.html ...
Parsing index_split_044.html ...
Parsing index_split_014.html ...
Parsing index_split_084.html ...
Parsing index_split_016.html ...
Parsing index_split_108.html ...
Parsing index_split_048.html ...
Parsing index_split_050.html ...
Parsing index_split_018.html ...
Parsing index_split_090.html ...
Parsing index_split_054.html ...
Parsing index_split_126.html ...
Parsing index_split_001.html ...
Parsing index_split_056.html ...
Parsing index_split_022.html ...
Parsing index_split_058.html ...
Parsing index_split_060.html ...
Parsing index_split_134.html ...
Parsing index_split_113.html ...
Parsing index_split_062.html ...
Parsing titlepage.xhtml ...
Parsing index_split_064.html ...
Parsing index_split_066.html ...
Parsing index_split_057.html ...
Parsing index_split_115.html ...
Parsing index_split_068.html ...
Parsing index_split_101.html ...
Parsing index_split_070.html ...
Parsing index_split_072.html ...
Parsing index_split_030.html ...
Parsing index_split_089.html ...
Parsing index_split_074.html ...
Parsing index_split_105.html ...
Parsing index_split_076.html ...
Parsing index_split_103.html ...
Parsing index_split_017.html ...
Parsing index_split_078.html ...
Parsing index_split_092.html ...
Parsing index_split_119.html ...
Parsing index_split_080.html ...
Parsing index_split_093.html ...
Parsing index_split_109.html ...
Parsing index_split_051.html ...
Parsing index_split_111.html ...
Parsing index_split_029.html ...
Parsing index_split_087.html ...
Parsing index_split_020.html ...
Parsing index_split_055.html ...
Parsing index_split_135.html ...
Parsing index_split_138.html ...
Parsing index_split_032.html ...
Parsing index_split_023.html ...
Parsing index_split_033.html ...
Parsing index_split_024.html ...
Parsing index_split_034.html ...
Parsing index_split_097.html ...
Parsing index_split_025.html ...
Parsing index_split_035.html ...
Parsing index_split_098.html ...
Parsing index_split_026.html ...
Parsing index_split_036.html ...
Parsing index_split_002.html ...
Parsing index_split_140.html ...
Parsing index_split_027.html ...
Parsing index_split_037.html ...
Parsing index_split_028.html ...
Parsing index_split_038.html ...
Parsing index_split_102.html ...
Parsing index_split_081.html ...
Parsing index_split_004.html ...
Parsing index_split_041.html ...
Parsing index_split_031.html ...
Parsing index_split_091.html ...
Parsing index_split_043.html ...
Parsing index_split_106.html ...
Parsing index_split_045.html ...
Parsing index_split_047.html ...
Parsing index_split_082.html ...
Parsing index_split_049.html ...
Parsing index_split_110.html ...
Parsing index_split_052.html ...
Parsing index_split_086.html ...
Parsing index_split_053.html ...
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 3823 items of level: p_1
Found 144 items of level: div_1
Negative text indent detected at level  p_1, ignoring this level
div_1  left margin stats: Counter()
div_1  right margin stats: Counter()
Cleaning up manifest...
Trimming unused files from manifest...
Trimming u'titlepage.xhtml' from manifest
Creating KePub Output...
2020-06-18 09:24:31 [DEBUG] Running ePub conversion
Splitting markup on page breaks and flow limits, if any...
	Looking for large trees in index_split_088.html...
	No large trees found
	Looking for large trees in index_split_021.html...
	No large trees found
	Looking for large trees in index_split_132.html...
	No large trees found
	Looking for large trees in index_split_059.html...
	No large trees found
	Looking for large trees in index_split_000.html...
	No large trees found
	Looking for large trees in index_split_003.html...
	No large trees found
	Looking for large trees in index_split_061.html...
	No large trees found
	Looking for large trees in index_split_063.html...
	No large trees found
	Looking for large trees in index_split_136.html...
	No large trees found
	Looking for large trees in index_split_114.html...
	No large trees found
	Looking for large trees in index_split_065.html...
	No large trees found
	Looking for large trees in index_split_099.html...
	No large trees found
	Looking for large trees in index_split_019.html...
	No large trees found
	Looking for large trees in index_split_067.html...
	No large trees found
	Looking for large trees in index_split_121.html...
	No large trees found
	Looking for large trees in index_split_122.html...
	No large trees found
	Looking for large trees in index_split_116.html...
	No large trees found
	Looking for large trees in index_split_071.html...
	No large trees found
	Looking for large trees in index_split_123.html...
	No large trees found
	Looking for large trees in index_split_039.html...
	No large trees found
	Looking for large trees in index_split_073.html...
	No large trees found
	Looking for large trees in index_split_124.html...
	No large trees found
	Looking for large trees in index_split_075.html...
	No large trees found
	Looking for large trees in index_split_125.html...
	No large trees found
	Looking for large trees in index_split_118.html...
	No large trees found
	Looking for large trees in index_split_077.html...
	No large trees found
	Looking for large trees in index_split_127.html...
	No large trees found
	Looking for large trees in index_split_107.html...
	No large trees found
	Looking for large trees in index_split_079.html...
	No large trees found
	Looking for large trees in index_split_128.html...
	No large trees found
	Looking for large trees in index_split_141.html...
	No large trees found
	Looking for large trees in index_split_015.html...
	No large trees found
	Looking for large trees in index_split_117.html...
	No large trees found
	Looking for large trees in index_split_129.html...
	No large trees found
	Looking for large trees in index_split_120.html...
	No large trees found
	Looking for large trees in index_split_083.html...
	No large trees found
	Looking for large trees in index_split_130.html...
	No large trees found
	Looking for large trees in index_split_069.html...
	No large trees found
	Looking for large trees in index_split_131.html...
	No large trees found
	Looking for large trees in index_split_142.html...
	No large trees found
	Looking for large trees in index_split_095.html...
	No large trees found
	Looking for large trees in index_split_133.html...
	No large trees found
	Looking for large trees in index_split_006.html...
	No large trees found
	Looking for large trees in index_split_139.html...
	No large trees found
	Looking for large trees in index_split_007.html...
	No large trees found
	Looking for large trees in index_split_096.html...
	No large trees found
	Looking for large trees in index_split_008.html...
	No large trees found
	Looking for large trees in index_split_137.html...
	No large trees found
	Looking for large trees in index_split_009.html...
	No large trees found
	Looking for large trees in index_split_046.html...
	No large trees found
	Looking for large trees in index_split_010.html...
	No large trees found
	Looking for large trees in index_split_143.html...
	No large trees found
	Looking for large trees in index_split_100.html...
	No large trees found
	Looking for large trees in index_split_013.html...
	No large trees found
	Looking for large trees in index_split_085.html...
	No large trees found
	Looking for large trees in index_split_011.html...
	No large trees found
	Looking for large trees in index_split_012.html...
	No large trees found
	Looking for large trees in index_split_005.html...
	No large trees found
	Looking for large trees in index_split_094.html...
	No large trees found
	Looking for large trees in index_split_040.html...
	No large trees found
	Looking for large trees in index_split_104.html...
	No large trees found
	Looking for large trees in index_split_042.html...
	No large trees found
	Looking for large trees in index_split_112.html...
	No large trees found
	Looking for large trees in index_split_044.html...
	No large trees found
	Looking for large trees in index_split_014.html...
	No large trees found
	Looking for large trees in index_split_084.html...
	No large trees found
	Looking for large trees in index_split_016.html...
	No large trees found
	Looking for large trees in index_split_108.html...
	No large trees found
	Looking for large trees in index_split_048.html...
	No large trees found
	Looking for large trees in index_split_050.html...
	No large trees found
	Looking for large trees in index_split_018.html...
	No large trees found
	Looking for large trees in index_split_090.html...
	No large trees found
	Looking for large trees in index_split_054.html...
	No large trees found
	Looking for large trees in index_split_126.html...
	No large trees found
	Looking for large trees in index_split_001.html...
	No large trees found
	Looking for large trees in index_split_056.html...
	No large trees found
	Looking for large trees in index_split_022.html...
	No large trees found
	Looking for large trees in index_split_058.html...
	No large trees found
	Looking for large trees in index_split_060.html...
	No large trees found
	Looking for large trees in index_split_134.html...
	No large trees found
	Looking for large trees in index_split_113.html...
	No large trees found
	Looking for large trees in index_split_062.html...
	No large trees found
	Looking for large trees in index_split_064.html...
	No large trees found
	Looking for large trees in index_split_066.html...
	No large trees found
	Looking for large trees in index_split_057.html...
	No large trees found
	Looking for large trees in index_split_115.html...
	No large trees found
	Looking for large trees in index_split_068.html...
	No large trees found
	Looking for large trees in index_split_101.html...
	No large trees found
	Looking for large trees in index_split_070.html...
	No large trees found
	Looking for large trees in index_split_072.html...
	No large trees found
	Looking for large trees in index_split_030.html...
	No large trees found
	Looking for large trees in index_split_089.html...
	No large trees found
	Looking for large trees in index_split_074.html...
	No large trees found
	Looking for large trees in index_split_105.html...
	No large trees found
	Looking for large trees in index_split_076.html...
	No large trees found
	Looking for large trees in index_split_103.html...
	No large trees found
	Looking for large trees in index_split_017.html...
	No large trees found
	Looking for large trees in index_split_078.html...
	No large trees found
	Looking for large trees in index_split_092.html...
	No large trees found
	Looking for large trees in index_split_119.html...
	No large trees found
	Looking for large trees in index_split_080.html...
	No large trees found
	Looking for large trees in index_split_093.html...
	No large trees found
	Looking for large trees in index_split_109.html...
	No large trees found
	Looking for large trees in index_split_051.html...
	No large trees found
	Looking for large trees in index_split_111.html...
	No large trees found
	Looking for large trees in index_split_029.html...
	No large trees found
	Looking for large trees in index_split_087.html...
	No large trees found
	Looking for large trees in index_split_020.html...
	No large trees found
	Looking for large trees in index_split_055.html...
	No large trees found
	Looking for large trees in index_split_135.html...
	No large trees found
	Looking for large trees in index_split_138.html...
	No large trees found
	Looking for large trees in index_split_032.html...
	No large trees found
	Looking for large trees in index_split_023.html...
	No large trees found
	Looking for large trees in index_split_033.html...
	No large trees found
	Looking for large trees in index_split_024.html...
	No large trees found
	Looking for large trees in index_split_034.html...
	No large trees found
	Looking for large trees in index_split_097.html...
	No large trees found
	Looking for large trees in index_split_025.html...
	No large trees found
	Looking for large trees in index_split_035.html...
	No large trees found
	Looking for large trees in index_split_098.html...
	No large trees found
	Looking for large trees in index_split_026.html...
	No large trees found
	Looking for large trees in index_split_036.html...
	No large trees found
	Looking for large trees in index_split_002.html...
	No large trees found
	Looking for large trees in index_split_140.html...
	No large trees found
	Looking for large trees in index_split_027.html...
	No large trees found
	Looking for large trees in index_split_037.html...
	No large trees found
	Looking for large trees in index_split_028.html...
	No large trees found
	Looking for large trees in index_split_038.html...
	No large trees found
	Looking for large trees in index_split_102.html...
	No large trees found
	Looking for large trees in index_split_081.html...
	No large trees found
	Looking for large trees in index_split_004.html...
	No large trees found
	Looking for large trees in index_split_041.html...
	No large trees found
	Looking for large trees in index_split_031.html...
	No large trees found
	Looking for large trees in index_split_091.html...
	No large trees found
	Looking for large trees in index_split_043.html...
	No large trees found
	Looking for large trees in index_split_106.html...
	No large trees found
	Looking for large trees in index_split_045.html...
	No large trees found
	Looking for large trees in index_split_047.html...
	No large trees found
	Looking for large trees in index_split_082.html...
	No large trees found
	Looking for large trees in index_split_049.html...
	No large trees found
	Looking for large trees in index_split_110.html...
	No large trees found
	Looking for large trees in index_split_052.html...
	No large trees found
	Looking for large trees in index_split_086.html...
	No large trees found
	Looking for large trees in index_split_053.html...
	No large trees found
2020-06-18 09:24:32 [WARN] The cover image has an id != "cover". Renaming to work around bug in Nook Color
2020-06-18 09:24:32 [DEBUG] Done ePub conversion
Python function terminated unexpectedly
  'module' object has no attribute 'KEPubContainer' (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1275, in run
  File "calibre_plugins.kepubout.conversion.kepub_output", line 108, in convert
AttributeError: 'module' object has no attribute 'KEPubContainer'

**Comment by jgoguen** [comment]
Fixed in v3.2.10 which was just published. Calibre should offer the update in the next couple hours if you don't manually install the packages from here.

**Comment by agrande985** [comment]
v3.2.10 works perfectly. thanks!

At 2020-06-18 12:22:04, "Joel Goguen" <notifications@github.com> wrote:

Fixed in v3.2.10 which was just published. Calibre should offer the update in the next couple hours if you don't manually install the packages from here.
