### ISSUE TITLE
More verbose error message when file transfer of multiple files fails due to 1 wrong epub

### ISSUE THREAD

**Issue by Northguy** [jgoguen/calibre-kobo-driver#110]
# Description

When transferring multiple books at once from Calibre to Kobo and one of those books is corrupt, the whole file transfer is aborted and a cryptic I/O error is thrown. Problem is that the offending title is not mentioned, which results in having to transfer all files one-by-one in order to find the offending file. 

It would be very nice if the title of the offending file is included in the error message. 
It would be even nicer if the file transfer for all good books is completed and only the one offending file fails in the transfer.

## Which plugins
KoboExtended

## Workarounds
Manually transfer smaller chunks of a multi-file transfer until offending title name is found. Repair the title and then continue with mass transfer

## How useful could this be

Every one that transfers multiple books at once and is not sure of the quality of the books being transfered can benefit, as it is time consuming to use the step-by-step approach to narrow down the transfer to find offending files.

## Additional context

Add any other information you think might be helpful.

**Comment by Northguy** [comment]
Example:

Transferring 13 book titles. One book has an error in html markup. Error thrown while transferring is non-descriptive with regard to the offending book title. Now step-by-step approach is needed in transferring, until offending file is found.

> 
> calibre, version 4.20.0
> ERROR: Error: Error communicating with device
> 
> [Errno 2] No such file or directory: u'C:\\Users\\***\\AppData\\Local\\Temp\\calibre_0ap_dv\\u6sgnn_epub_container\\.html'
> 
> Traceback (most recent call last):
>   File "site-packages\calibre\gui2\device.py", line 90, in run
>   File "site-packages\calibre\gui2\device.py", line 594, in _upload_books
>   File "calibre_plugins.kobotouch_extended.device.driver", line 397, in upload_books
>   File "site-packages\calibre\devices\kobo\driver.py", line 2121, in upload_books
>   File "calibre_plugins.kobotouch_extended.device.driver", line 283, in _modify_epub
>   File "calibre_plugins.kobotouch_extended.common", line 193, in modify_epub
>   File "calibre_plugins.kobotouch_extended.container", line 271, in forced_cleanup
>   File "site-packages\calibre\ebooks\oeb\polish\container.py", line 604, in raw_data
>   File "site-packages\calibre\ebooks\oeb\polish\container.py", line 1063, in open
>   File "site-packages\calibre\startup.py", line 169, in local_open
> IOError: [Errno 2] No such file or directory: u'C:\\Users\\****\\AppData\\Local\\Temp\\calibre_0ap_dv\\u6sgnn_epub_container\\.html'
>

**Comment by Northguy** [comment]
Issue with book that needs to be fixed is:

ERROR: Empty id attributes are invalid    [OEBPS/content.opf]
**ERROR: Item (../.html) in manifest is missing    [OEBPS/content.opf]**
WARNING: Named entities present    [OEBPS/Text/Section0025.xhtml]
WARNING: The linked resource '../.html' does not exist    [OEBPS/content.opf]

**Comment by jgoguen** [comment]
Without the full and complete debug log the bug template requires you to include it's difficult to tell, but it looks like you have the option to skip failed conversions disabled. If you configure the driver to skip failed conversions, it will copy any books that fail conversion to the Kobo device as standard ePub files.

I can work on including this in the exception message, but without the information required from the bug report template I can't promise it will actually fix the issue you're reporting.

**Comment by Northguy** [comment]
Thank you. Will test once available.
