### ISSUE TITLE
Obfuscation conversion error for some but not all AZW3 files

### ISSUE THREAD

**Issue by KarenLMyers** [jgoguen/calibre-kobo-driver#133]
Thanks for looking at this -- I appreciate your guidance. If this should be reported to someone else, please let me know.

[ With apologies, I am not a regular GitHub user. Will I receive any email prompt from GitHub about a response or do I have to keep checking back? ]

------------------

Calibre 5.8.1 64-bit (12/31/20)
Most recent plugins as of 12/31/20 for all plugins

My (many years) process for converting my own Amazon ebooks for use on my Kobo Reader works for almost all my recent downloads (using the Kindle 1.17.0 for downloading from Amazon). A few books are failing to convert to KEPUB (or to ordinary EPUB).

My usual method of conversion is simply to drag the AZW format to the connected device. For this report, I used the "Convert file to Epub" with selection "KEPUB" and no other changes -- same results as my usual method.

I first observed this for a book published circa 10/27/2020. That is the first example below (file tmpo6foybf3.txt).

Error msg:
 File "calibre\ebooks\oeb\polish\container.py", line 1342, in process_encryption
calibre.ebooks.oeb.polish.container.ObfuscationKeyMissing: Failed to find obfuscation key
----

Calibre debug log attached

[tmpo6foybf3.txt](https://github.com/jgoguen/calibre-kobo-driver/files/5758184/tmpo6foybf3.txt)

----------------------
2nd example -- older book (several years, recently downloaded). (File: tmp6buqsjl2.txt)

Error msg:   File "calibre\ebooks\oeb\polish\container.py", line 1342, in process_encryption
calibre.ebooks.oeb.polish.container.ObfuscationKeyMissing: Failed to find obfuscation key
----

Calibre debug log attached

[tmp6buqsjl2.txt](https://github.com/jgoguen/calibre-kobo-driver/files/5758187/tmp6buqsjl2.txt)

**Comment by jgoguen** [comment]
@KarenLMyers Unfortunately this is happening within calibre itself. It's either a calibre bug or something weird with some AZW3 books (or both).

You might be able to work around it by converting to ePub first and then to KePub (using the KePub Output extension). If you edit the KoboTouchExtended driver options to put `kepub` at the top of the format list the driver won't attempt to re-convert when a KePub format already exists.

Unfortunately that isn't always working. There were a couple books, otherwise DRM-free even, where I had to remove the fonts from the book entirely to get it to convert successfully.

**Comment by KarenLMyers** [comment]
Just wanted to get back to you to reports the results.

After taking a turn with Kovid Goyal (and not finding anything short of KePUB Conversion, where he handed it back) the following process works:

1) Import Amazon AZW3 file. (DeDRM runs, stashes result AZW3 file in Calibre local library)

2) "Manually" convert to EPUB (no errors)

3) "Manually" convert the EPUB file to KEPUB [no errors] (as you recommended) [manually converting from the AZW3 directly to KEPUB continues to produce the error].

4) Move the book's KEPUB file to the KoboTouchExtended device (which was already in the order "KEPUB, EPUB, ...").

This works, and I can use this workaround as needed (thanks!)

Now if I can only get my user-defined shelves/collections to be recognized by Kobo -- this broke some months ago and I haven't reported a bug. I'm off to find out if anyone else did.... :)
