### ISSUE TITLE
ERROR: can't start new thread

### ISSUE THREAD

**Issue by Neurosploit** [jgoguen/calibre-kobo-driver#135]
I'm trying to convert an epub file from delphi classics (https://www.delphiclassics.com/shop/seneca-the-younger/) to kepub. This is a fairly large epub in terms of pages (not file size) with a few thousand pages.
I'm using the latest kepub plugin version (3.4.4) and am running into a threading problem during conversion.
The problem occurs during the output (processing) step of the conversion.

Exception in thread Thread-10689:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "calibre_plugins.kepubout.container", line 547, in add_kobo_spans
  File "calibre_plugins.kepubout.container", line 183, in flush_cache
  File "calibre_plugins.kepubout.container", line 409, in __run_async
  File "calibre_plugins.kepubout.container", line 409, in <listcomp>
  File "threading.py", line 852, in start
RuntimeError: can't start new thread

I've looked at the changelog and I see that in version 3.3.0 multi-threading was added.
So I've switched back to 3.2.15 and worked around the KeyError: "There is no item named 'css/style-hacks.css' in the archive" exception that I got with that version by adding the css to the kepub output zip and re-zipping the plugin. That conversion completed without any issues so I'm expecting it to be somewhere in the multithreading code.

Side-note: I'm trying to convert this on a 12-core ryzen cpu with hyperthreading enabled so I would expect to have quite a few threads available to me. My calibre version is 5.3.0.

Gist with the complete conversion log: https://gist.github.com/Neurosploit/623c03465dd5b5d395e876c3a8acf67c

**Comment by jgoguen** [comment]
New version 3.5.1 should fix this, it uses a process pool and multiple processes instead of spinning up a thread per content file.
