### ISSUE TITLE
Converted KePub files randomly contain empty chapters

### ISSUE THREAD

**Issue by Crazyphil** [jgoguen/calibre-kobo-driver#139]
# Bug Checklist

These items are mandatory. If you need help finding this information submit the
bug report with as much completed as you can and ask for help finding the rest.

- [X] I am using the latest version of calibre to report this bug, which is: 5.31.1
- [X] I am using an official calibre release, not one from a third party (e.g.
    your Linux distro, Flatpak, Chocolatey package, Homebrew, etc.)
- [X] I am using the latest version of this plugin, which is: 3.5.4
- [X] My operating system is (e.g. Windows 10, Windows 8.1, Windows 8, macOS
    10.15.5, Fedora 32, Arch Linux, etc.): Windows 10
- [X] I have included the full, complete, unmodified debug log from calibre
  - Directions for getting the debug log are under the "Logs" header below.
- [X] I have translated the text in any screenshots and logs to English, or all
    screenshots and logs included are in English.

These items are optional. Fill in as much of them as possible. If something is
not applicable to your bug report, note that.

- [X] I have installed the Scramble Epub plugin (see
    https://www.mobileread.com/forums/showthread.php?t=267998) and will attach
    a **scrambled** copy of the book I'm having problems with (attach a file by
    dragging and dropping onto the Github editor).
[To Sleep in a Sea of Stars - Christopher Paolini_scrambled.epub.zip](https://github.com/jgoguen/calibre-kobo-driver/files/7452838/To.Sleep.in.a.Sea.of.Stars.-.Christopher.Paolini_scrambled.epub.zip)
  - [X] If this is a conversion bug, I will also attach a **scrambled** copy of
    the converted book.
[To Sleep in a Sea of Stars - Christopher Paolini_scrambled.kepub.epub.zip](https://github.com/jgoguen/calibre-kobo-driver/files/7452887/To.Sleep.in.a.Sea.of.Stars.-.Christopher.Paolini_scrambled.kepub.epub.zip)
- [X] The path to my calibre library or to a book in my calibre library has
    non-ASCII characters: no

- [X] If I am using Windows 10, I (have/have not) enabled Windows' beta support
      for Unicode (see
      https://www.mobileread.com/forums/showpost.php?p=3988195&postcount=2052)
- [ ] If I am using Windows 10, does this bug happens with beta Unicode support
    both enabled and disabled, only when enabled, or only when disabled?

# Describe the bug

Converted KePub files randomly contain empty chapters. The converted HTML files contain the full `head`, but no `body`. The `title` tag is set to _Unbekannt_ ("unknown") instead of the correct chapter title.

## Steps to Reproduce

Steps to reproduce the behavior (as detailed as you can):

1. Plug in the Kobo reader
2. Right-click the eBook in the library
3. Choose 'Send to device'
4. Click 'Send to main storage'
5. Wait for the operation to finish
6. Unplug the device
7. Let the reader refresh its library
8. Open the converted eBook (either on-device, or using Calibre's eBook viewer)
9. Navigate to one of the now empty chapters. In the scrambled KePub file I attached, the concerning chapter is _Dvqbxgq_ (`chapter4.xhtml`).

## Expected behavior

All chapters are converted including their content.

## Actual behaviour

Some chapters of converted ePub files are empty. When reproducing the bug using the latest Calibre and plugin version, I noticed that fewer chapters are now empty than when I last converted it in August. Then, in addition to Chapter 4, also Chapter 40 (_Bmkwdjcjwz_) and Chapter 41 (_Bcevn Npcezcoad_) were empty.

## Screenshots

Not applicable

## Logs

Restart calibre in debug mode. Paste the full calibre debug log here. To get the
debug log:

1. Find the `Preferences` button in the calibre toolbar.
1. Click the arrow to the right of `Preferences`.
1. Select the `Restart in debug mode` menu item.
   1. This will shut down and restart calibre immediately. Calibre will
      automatically restart, but it may take a few seconds.
   1. You will see a notification informing you that you have started calibre
      in debug mode. Click `OK`.
1. Do the minimum possible steps to reproduce the bug.
1. Close calibre.
   1. This will automatically display the debug log. Copy and paste the entire
      log in the blank space here (between `` ```text `` and `` ``` ``)

[tmp1xyoubid.txt](https://github.com/jgoguen/calibre-kobo-driver/files/7452830/tmp1xyoubid.txt)

## Additional context

See the scrambled (K)ePub files inbetween the checklist bullet points at the top.

**Comment by jgoguen** [comment]
Apologies for the extremely delayed response. I'm not able to reproduce this in calibre 5.32, can you update calibre and see if it's still a problem?

**Comment by Crazyphil** [comment]
Yes, the issue seems to have resolved itself. Thank you for investigating.
