### ISSUE TITLE
Clarification of a request in the README file

### ISSUE THREAD

**Issue by TechTomator** [jgoguen/calibre-kobo-driver#141]
In the README file, there is this paragraph:

_| **Special Note**
| You should turn off the built-in KoboTouch driver (authored by David Forrester) while using this plugin. 
| On rare occasions, calibre may inadvertently select the built-in KoboTouch driver instead of this plugin. 
| But do not turn off the built-in Kobo driver._

It would help noobs like me if there was a line of info on how / where we can turn off the KoboTouch driver; or how we can verify that it is indeed turned off.  (and check that the Kobo driver is still on.)

Many thanks for your work on the plugin!

**Comment by jgoguen** [comment]
Thanks for that! This hasn't actually been a problem for a while as far as I can tell, so it's probably better to just remove that entirely.
