### ISSUE TITLE
Libra 2

### ISSUE THREAD

**Issue by FredGHF** [jgoguen/calibre-kobo-driver#142]
# Description

Is it correct The libra 2 is not supporter yet?

Add any other information you think might be helpful.

**Comment by davidfor** [comment]
Libra 2 support was included in the last release of the driver. But, most of the support for devices is in the KoboTouch driver built-in to calibre. The only device specific code in the extended driver is to set the name of the CSS file used for the "Modify CSS" option. If the extended driver is not updated for a new device, the CSS file will be the default of "kobo_extra.css".

**Comment by jgoguen** [comment]
Libra 2 is supported, but I forgot to add it to the README file. I've updated that with the other device-specific CSS files as well.

**Comment by FredGHF** [comment]
Dear Joel,

thank you for your reply.
Today I checked the plug-n again in combination with my Kobo Libra 2, and it works perfect, but only after I gave Calibre read/write access to the external drive form Kobo.

Best regards,
Fred.
