### ISSUE TITLE
UniCodeDecodeError

### ISSUE THREAD

**Issue by ksbrwr** [jgoguen/calibre-kobo-driver#149]
I get this error on my Kobo Aura ONE when it tries to obtain the list of books:

--- start error message ---
calibre, version 6.3.0
FOUT: Fout: Fout bij communicatie met toestel

'utf-8' codec can't decode byte 0x9b in position 9: invalid start byte

Traceback (most recent call last):
  File "calibre\gui2\device.py", line 88, in run
  File "calibre\gui2\device.py", line 540, in _books
  File "calibre\devices\kobo\driver.py", line 2024, in books
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 9: invalid start byte
--- end error message ---

Calibre version: 6.3.0
Kobo Aura ONE softwareversion: 4.33.19759

**Comment by jgoguen** [comment]
This exception is coming from the base Kobo driver that comes with calibre, not this driver.
