### ISSUE TITLE
name of file after converting EPUB to KEPUB

### ISSUE THREAD

**Issue by napotri** [jgoguen/calibre-kobo-driver#152]
# Description

ON my Kobo (s) the name of KEPUB file must end with the extension .kepub.epub to be recognized. With the actual extension, .kepub, the book are not seen by KOBO.

## Which plugins

Kepub output 3.6.3

## Workarounds

IN calibre, there is no impact when I use the fonction send to (I have a good extension on my kobo) but if I use write to disk I have only the extension  .kepub. The same I Obtain when I convert to Kepub.

## How useful could this be

It will be useful when I send a kepub book by mail ou copy with a USB Key.

## Additional context

Add any other information you think might be helpful.

**Comment by jgoguen** [comment]
When stored on a Kobo device, the file must have the double `.kepub.epub` extension to be picked up as a "Kobo ePub". Calibre only supports single extensions, hence `.kepub` alone is used in calibre. If you're trying to send the files by any means other than uploading to a Kobo device via calibre, you need to manually rename the files to have the correct extension. Note that if you're on Windows or macOS file extensions may be hidden, you'll need to enable display of file extensions to be able to properly rename the files.
