### ISSUE TITLE
Add support for 4.34.20097 firmware

### ISSUE THREAD

**Issue by sergeykad** [jgoguen/calibre-kobo-driver#153]
# Description

The 4.34.20097 firmware version released on September 2022 is not supported severely limiting books synchronization options in Calibre.
Calibre prints an error when trying to sync that the version is not supported.

**Comment by jgoguen** [comment]
This driver supports whatever version the base driver in calibre supports. Any version updates need to be made there. That's not a bug, these updates happen as part of the regular calibre release cycle. If you don't want to wait, and risk breaking something, you can update the driver settings to attempt to work with unsupported versions.
