### ISSUE TITLE
Process for importing (new?) Amazon Kindle Unlimited Voucher-associated file content 

### ISSUE THREAD

**Issue by KarenLMyers** [jgoguen/calibre-kobo-driver#157]
# Bug Checklist

These items are mandatory. If you need help finding this information submit the
bug report with as much completed as you can and ask for help finding the rest.

- [Yes ] I am using the latest version of calibre to report this bug, which is: 6.11, updated 1/11/2023. There are no outstanding plugin updates available
- [Yes] I am using an official calibre release, not one from a third party (e.g.
    your Linux distro, Flatpak, Chocolatey package, Homebrew, etc.)
- [Yes] I am using the latest version of this plugin, which is:
- [Win 10 ] My operating system is (e.g. Windows 10, Windows 8.1, Windows 8, macOS
    10.15.5, Fedora 32, Arch Linux, etc.):
- [Yes ] I have included the full, complete, unmodified debug log from calibre - 
  - Directions for getting the debug log are under the "Logs" header below.
- [ Yes] I have translated the text in any screenshots and logs to English, or all
    screenshots and logs included are in English.

These items are optional. Fill in as much of them as possible. If something is
not applicable to your bug report, note that.

- [No] I have installed the Scramble Epub plugin (see
    https://www.mobileread.com/forums/showthread.php?t=267998) and will attach
    a **scrambled** copy of the book I'm having problems with (attach a file by
    dragging and dropping onto the Github editor).
  - [No ] If this is a conversion bug, I will also attach a **scrambled** copy of
    the converted book.
- [No ] The path to my calibre library or to a book in my calibre library has
    non-ASCII characters: yes/no
- [No ] If I am using Windows 10, I (have/have not) enabled Windows' beta support
      for Unicode (see
      https://www.mobileread.com/forums/showpost.php?p=3988195&postcount=2052)
- [ NA] If I am using Windows 10, does this bug happens with beta Unicode support
    both enabled and disabled, only when enabled, or only when disabled?

# Describe the bug

*** This may be an outstanding import or plugin lack of programming issue for a new Amazon feature, rather than a bug per se. ***

For the very first time, I have encountered a Kindle Unlimited file which forced an update to my existing Kindle Previewer program (otherwise refused to download) (I had been using the 2017 version, since more recent ones were triggering ). The Kindle update ran properly and the content of the Kindle library looked normal in the Kindle Previewer. The book file(s) downloaded. 

From that point, there were differences. Instead of receiving via Kindle Previewer a conventional .AZW file from Amazon [for which my Calibre import process has been: copy AZW file, rename FILENAME, move to a Calibre-accessing directory, and then load into Calibre & manage in a normal fashion], I received a HIGHLEVEL FOLDER with a SUBFOLDER of files, only one of which was an .AZW file, under a new FOLDER. See following list.

Downloaded from Amazon via Kindle Previewer: 
   * Folder: My Kindle Content [NEW FOLDER]
   ** SubFolder: B0BQC1WMF9_EBOK [the selected KU book's Amazon product code]
   ** ** Sub Folder: B0BQC1WMF9_EBOK.mbpV2
   ** ** Sub Folder: CR!DXSZ0ZB2FH1BVDG6S95WMQSXQP09.azw.res
   ** ** Sub Folder: CR!90SKK3STHD48D5S7R7RMNZSJ2599.azw.md
   ** ** Sub Folder: B0BQC1WMF9_EBOK.azw
   ** ** Sub Folder: amzn1.drm-voucher.v1.945bd125-7a81-44b0-8831-5ab1c251689d.voucher
   ** SubFolder: NoteDocuments [empty]

I did try my old method of copying the B0BQC1WMF9_EBOK.azw file to my Calibre directory, but the metadata informs me that it is in the format of "KFX-ZIP".

QUESTION: What is the best method (if any) of taking the downloaded files in the SubFolder: B0BQC1WMF9_EBOK folder and migrating an appropriate file(s) to the Calibre folder that I've been using for all my books, up to now? 

SUB-QUESTION: I presume that, if I can reconstruct the zipped AZW file by some method, that the plugin files for output to KOBO and unrestricted MOBI/AZW either exist or are in process. Is that correct?

SUB-QUESTION: If this will require a new feature or plugin(s), how can I keep track of that?

## Steps to Reproduce

Steps to reproduce the behavior (as detailed as you can):

[See above]

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

That the Amazon download AZW format would still be self-contained. Or, if not, that the Amazon old-style AZW file could be reassembled from the folder contents above (either by plugin or manually by me). Or that there is some method of making this work.

## Actual behaviour

Amazon has changed its file structure philosophy from self-contained AZW to a folder of files. How can I digest this?

## Screenshots

If applicable, add screenshots to help explain your problem. If you are using
calibre in any language other than English, please either provide a translation
of any relevant text to English or switch calibre to use English first.

## Logs

Restart calibre in debug mode. Paste the full calibre debug log here. To get the
debug log:

1. Find the `Preferences` button in the calibre toolbar.
1. Click the arrow to the right of `Preferences`.
1. Select the `Restart in debug mode` menu item.
   1. This will shut down and restart calibre immediately. Calibre will
      automatically restart, but it may take a few seconds.
   1. You will see a notification informing you that you have started calibre
      in debug mode. Click `OK`.
1. Do the minimum possible steps to reproduce the bug.
1. Close calibre.
   1. This will automatically display the debug log. Copy and paste the entire
      log in the blank space here (between `` ```text `` and `` ``` ``)

```text
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.11  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 50, 0) && Copy Cover To Device (2, 0, 4) && Count Pages (1, 12, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0) && KePub Input (3, 6, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 3) && Kobo Utilities (2, 16, 6) && KoboTouchExtended (3, 6, 3)
calibre 6.11  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 50, 0) && Copy Cover To Device (2, 0, 4) && Count Pages (1, 12, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0) && KePub Input (3, 6, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 3) && Kobo Utilities (2, 16, 6) && KoboTouchExtended (3, 6, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.62] db initialized
[0.62] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864, 'width': 1536, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 871, 'width': 1474, 'x': 62, 'y': -7},
 'full_screened': False,
 'geometry': {'height': 841, 'width': 1474, 'x': 62, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 841, 'width': 1474, 'x': 62, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.25,
            'geometry_in_logical_pixels': {'height': 864,
                                           'width': 1536,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 864, 'width': 1536},
            'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864, 'width': 1536, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 841, 'width': 1474, 'x': 62, 'y': 23}
Restoring widget to maximized
DEBUG:    1.4 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    1.4 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    1.4 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    1.4 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
[2.34] main UI initialized...
[2.34] Hiding splash screen
Starting QuickView
Storage number map:
{(7, 0): [(4, 'C')], (7, 1): [(1, 'G')], (7, 2): [(1, 'E')], (7, 3): [(1, 'H')]}
Storage number for USBSTOR\DISK&VEN_LINUX&PROD_FILE-STOR_GADGET&REV_0401\N249141125561&0: StorageDeviceNumber(type=7, number=3, partition_number=0)
Drive letters for USBDevice(vendor_id=0x2237 product_id=0x4228 bcd=0x401 devid=usb\vid_2237&pid_4228&rev_0401 devinst=15)
{'drive_letters': ['H'],
 'pnp_id_map': {'H': '\\\\?\\usbstor#disk&ven_linux&prod_file-stor_gadget&rev_0401#n249141125561&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'H': (3, 1)}}
DEBUG:   17.4 KoboUtilities:_on_device_connection_changed - self.plugin_device_connection_changed.__class__:  <class 'PyQt6.QtCore.pyqtBoundSignal'>
DEBUG:   17.4 Methods for self.plugin_device_connection_changed:  ['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'connect', 'disconnect', 'emit', 'signal']
DEBUG:   17.4 Have a Kobo device connected connected
DEBUG:   17.4 BEGIN Get Device Path
DEBUG:   17.4 Root path of device: H:\
DEBUG:   17.4 END Get Device Path
DEBUG:   17.4 KoboUtilities:get_device - self.device_path="H:\"
DEBUG:   17.4 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:   17.4 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 KoboTouch:books - oncard='None'
2023-01-11 12:40:07 [DEBUG] KoboTouchExtended:settings: settings= 
```

## Additional context

Add any other information you think might be helpful.

**Comment by KarenLMyers** [comment]
I have verified that Kindle Unlimited is not a specific factor. An ordinary Kindle book also triggers the same issue.

**Comment by jgoguen** [comment]
I know nothing about using Kindle Previewer, so I can't support it, but I would assume that `B0BQC1WMF9_EBOK.azw` is the AZW file you want to add to calibre. You can usually download books directly from https://www.amazon.com/hz/mycd/digital-console/contentlist/booksAll/dateDsc/ using the "More actions" menu beside each book though. Note that not all books are available for downloading, particularly Kindle Unlimited books. Importing from Amazon typically requires breaking DRM however, which I'm unable to provide any support for as it's not legal in the United States. If you have a DRM-free book from Amazon, however, please try downloading it from the link above and see if that works. 

If you still need help, I can only support issues with sending the book to your device using this driver (which is what I need a debug log of you doing). For anything else I'd look to different groups on https://www.mobileread.com depending on what exactly you're looking for help with (Amazon Kindle for help with Kindle Previewer and identifying which file to import to calibre, Calibre for trouble getting the downloaded file imported).
