### ISSUE TITLE
synopsis not loaded

### ISSUE THREAD

**Issue by mnijskens** [jgoguen/calibre-kobo-driver#164]
Hi Joel
thanks for the kepub plugin for Calibre.  A lot of times the synopsis is not loaded to my Kobo Aura One when i have converted my books with the plugin 
Is this a know problem ? Can I solve it myself ?
Curious about your answer

Marcel Nijskens

**Comment by jgoguen** [comment]
This plugin doesn't modify metadata at all. It doesn't even send books to a device. All it does is hook in to the built-in Kobo device driver and modifies content files (not metadata) just before the book is sent by the built-in Kobo device driver.

If you can get debug logs showing this happening I can see if there's anything I can do about it, but I haven't been able to reproduce it and it doesn't look like something this plugin touches.
