### ISSUE TITLE
status of Python 3 port?

### ISSUE THREAD

**Issue by sten0** [jgoguen/calibre-kobo-driver#78]
Hi @jgoguen,

Thank you for maintaining this plugin!  In Debian, the Python Team is aggressively pursuing the removal of all Python 2 packages (imho too aggressively, but I digress).  In a second worst case scenario, the experimental Python 3 only branch of Calibre will be the only available package, and all Python 2 plugins will break.  The worst case scenario is of course that basic functionality in a py3-only Calibre won't be ready in time.

Your kepub driver is the plugin that I care about the most, and I suspect also one of the most important to libraries where Calibre is often used, which is why I'm reaching out now :-)

Would it be possible to have a working Python 3 port of this driver by 1 Jan 2020 (Python 2 EOL)?  This also affects users of all derived distributions such as Ubuntu, Mint, Elementary, etc.

Sincerely,
Nicholas

P.S. If you could reach out to your contacts in the greater Calibre developer community and spread the word, I would very much appreciate it!

**Comment by jgoguen** [comment]
The only supported calibre is the one Kovid packages, which is still Python 2. So although I prefer Python 3 (and actually disagree the Debian Python team is being too aggressive, Python 2 EOL hasn't been any surprise for a long time now) I have to remain Python 2.

What I can attempt to do is to have a 2/3 compatible version. I make no promises on the date. I don't have a working Kobo device right now (nor when I can acquire one) so I can't properly test it, nor will I be testing on a Python 3 calibre until Kovid is looking for testers, so all I can even promise for the driver plugin will be a syntactically correct script that the supported calibre loads properly.

**Comment by norbusan** [comment]
Hi @jgoguen 
Debian maintainer of Calibre and Kobo user here.
Thanks for your answerm and I fully understand your reasoning.
If you can ensure Py 2/3 compatibility I can test it on my system and with my Kobo.

All the best

Norbert

**Comment by jgoguen** [comment]
@norbusan check out the `py3k` branch. I've only done basic testing so far for Python 2 compatibility but it looks OK so far.

In the `py3k` checkout run `make` to get a zip file created for each plugin. Those can be installed in calibre's plugins dialog using `Load plugin from file`.

**Comment by norbusan** [comment]
Hi @jgoguen 
thanks, I finally ave all the ingredients running in Debian to compile/run a Python3 based Calibre. I will test the code of yours ASAP (ie, when I am back from my travel and have access to my device).

Thanks!

**Comment by norbusan** [comment]
Hi @jgoguen 
I finally came around trying your branch, but unfortunately I cannot even load the plugin:
```
calibre, version 4.2.0
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name 'KOBOTOUCHEXTENDED' from 'calibre_plugins.kobotouch_extended.device.driver' (<calibre Plugin Loader>)

calibre 4.2  embedded-python: False is64bit: True
Linux-5.3.8-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.3.8', '#5 SMP Wed Oct 30 08:45:29 JST 2019')
Python 3.7.5
Linux: ('debian', 'bullseye/sid', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 19, 0) && Package KFX (from KFX Input) (1, 19, 0) && Amazon.com Multiple Countries (1, 0, 0) && Generate Cover (1, 5, 21) && Goodreads Sync (1, 12, 1) && Hyphenate This! (0, 0, 8) && KFX metadata reader (from KFX Input) (1, 19, 0) && KFX Input (1, 19, 0) && KePub Input (3, 0, 0) && KePub Metadata Reader (3, 0, 2) && KePub Output (3, 1, 3) && KindleUnpack - The Plugin (0, 81, 5) && Kobo Utilities (2, 8, 0) && Obok DeDRM (6, 5, 4)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 201, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 113, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 628, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 185, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.kobotouch_extended.__init__", line 9, in <module>
ImportError: cannot import name 'KOBOTOUCHEXTENDED' from 'calibre_plugins.kobotouch_extended.device.driver' (<calibre Plugin Loader>)
```

**Comment by jgoguen** [comment]
That is unfortunately rather unhelpful. Can you put your Python 3 calibre package somewhere I can get it to try on my own system? I use Fedora but I can unpack the deb and it should run fine.

**Comment by norbusan** [comment]
Hi
please get `calibre` from one of the mirrors here: https://packages.debian.org/experimental/all/calibre/download
and `calibre-bin` from one of the mirrors here https://packages.debian.org/experimental/amd64/calibre-bin/download (assuming you are on amd64)

These are the packages that are in experimental.

Thanks

**Comment by jgoguen** [comment]
This may be more difficult than expected. The Debian version won't run, it complains about some Python library being called with the wrong name. But Fedora also has a Python 3 package of calibre and the plugin loads perfectly fine for me.

Can you try something for me? Move `~/.config/calibre` out of the way, to start with a fresh profile, then start calibre with `calibre-debug -g`. Clone this repo and switch to the `py3k` branch and run `make` to build the ZIP files. In calibre, use Load From File to install these new ZIP files. If that blows up, can you include the full output from `calibre-debug -g`?

**Comment by norbusan** [comment]
Hi @jgoguen 
you are right, I can install without problems into a clean calibre/python3 installation. I guess the problem is because I have some other plugins or old settings hanging around that doesn't allow updating. 

After manually removing all plugins related to Kobo in the .config/calibre/plugins directory (that anyway didn't load under Py3), I could install the py3 branch version on Calibre/Py3.

I will test it with my device tonight when I am back home.

**Comment by rgessner** [comment]
Hello,

first of all, thanks for the great work with this plugin.
I have problems with the installation on Fedora 31.

Fedora 31, latest updates installed.
ZIPs from the git clone of the `py3k` branch.

I encounter the following error.
(Output from `calibre-debug -g` with empty `.config/calibre` dir)

```
calibre 4.1  embedded-python: False is64bit: True
Linux-5.3.11-300.fc31.x86_64-x86_64-with-fedora-31-Thirty_One Linux ('64bit', 'ELF')
('Linux', '5.3.11-300.fc31.x86_64', '#1 SMP Tue Nov 12 19:08:07 UTC 2019')
Python 3.7.5
Linux: ('Fedora', '31', 'Thirty One')
Interface language: None
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.84180790960451 x 91.7458193979933
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.07] splash screen shown
[0.07] Initializing db...
[0.07] db initialized
[0.07] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.90] main UI initialized...
[0.90] Hiding splash screen
[0.98] splash screen hidden
[0.98] Started up in 0.98 seconds with 1 books
calibre 4.1  embedded-python: False is64bit: True
Linux-5.3.11-300.fc31.x86_64-x86_64-with-fedora-31-Thirty_One Linux ('64bit', 'ELF')
('Linux', '5.3.11-300.fc31.x86_64', '#1 SMP Tue Nov 12 19:08:07 UTC 2019')
Python 3.7.5
Linux: ('Fedora', '31', 'Thirty One')
Interface language: None
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/preferences/plugins.py", line 318, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 202, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.kobotouch_extended.__init__", line 9, in <module>
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.kobotouch_extended.device.driver", line 14, in <module>
ModuleNotFoundError: No module named 'ConfigParser'
```

`python3-configparser-3.7.1-3.fc31.noarch` is installed.

```
$ pip  list | grep -i config
configparser       3.7.1   
```   

Any hints what could be wrong?

**Comment by jgoguen** [comment]
This is puzzling, line 14 is `from datetime import datetime`, nothing to do with `ConfigParser`.

But if I ignore line numbers, the next thing that happens is (basically):

- Try to import `configparser`
  - This is the Python 3 module name
- If `configparser` fails, import `ConfigParser`
  - `ConfigParser` is the Python 2 module name

So if you're using a Python 3 calibre build, I would absolutely expect it would fail to import `ConfigParser`. but I'm curious why it's not finding the `configparser` module. Check to see if `/usr/lib64/python3.7/configparser.py` exists? That's supposed to be provided by `python3-libs`, not something you should install from `pip` (but even if you do it should still find it, unless `pip` installed to your user location, which isn't in `sys.path` by default).

Check a few things:

- Run `locate configparser.py`. You can ignore anything not under `/usr/lib64/python3.7`, `/usr/lib/python3.7`, or your home directory (and some locations in there should be ignored anyway). You should at least see one entry in your `sys.path`.
- Run `python3`, the at the python prompt enter `import configparser`. That should just drop you back to the prompt with no output, if there's any output it should be a stacktrace saying importing failed (and should say it's an `ImportError`).
- Run `pip show configparser` and see what directory is listed for `Location`. Run `python3`, then enter `import sys`, then enter `sys.path` to get a list of your Python import paths. If the directory listed in `Location` isn't in `sys.path` Python won't find it.

**Comment by rgessner** [comment]
Thanks for your answer.
I tried so far:

```
$ locate configparser.py
/usr/lib/python2.7/site-packages/configparser.py
/usr/lib/python2.7/site-packages/configparser.pyc
/usr/lib/python2.7/site-packages/configparser.pyo
/usr/lib/python3.7/site-packages/configparser.py
/usr/lib64/python3.7/configparser.py
```
```
$ dnf provides /usr/lib64/python3.7/configparser.py
Last metadata expiration check: 0:18:30 ago on Sat 16 Nov 2019 06:59:14 PM CET.
python3-libs-3.7.4-5.fc31.x86_64 : Python runtime libraries
Repo        : fedora
Matched from:
Filename    : /usr/lib64/python3.7/configparser.py

python3-libs-3.7.5-1.fc31.x86_64 : Python runtime libraries
Repo        : @System
Matched from:
Filename    : /usr/lib64/python3.7/configparser.py

python3-libs-3.7.5-1.fc31.x86_64 : Python runtime libraries
Repo        : updates
Matched from:
Filename    : /usr/lib64/python3.7/configparser.py
```
I also confirmed the sha256sum of the actual file with the info in the rpm package. OK.



Next one:

```
$ which python
/usr/bin/python
$ ls -l /usr/bin/python
lrwxrwxrwx. 1 root root 9 Oct 17 13:54 /usr/bin/python -> ./python3


$ python
Python 3.7.5 (default, Oct 17 2019, 12:16:48) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
>>> import sys
>>> sys.path
['', '/usr/lib64/python37.zip', '/usr/lib64/python3.7', '/usr/lib64/python3.7/lib-dynload', '/usr/lib64/python3.7/site-packages', '/usr/lib/python3.7/site-packages']
>>> 

$ rpm -qa | grep configparser
python2-configparser-3.7.1-3.fc31.noarch
python3-configparser-3.7.1-3.fc31.noarch

```
Again, nothing suspicious. 
After the fedora31 release i installed the machine from scratch, so there should be no problem with some old garbage floating around.

Are there any additional debug flags i can set on calibre-debug to further investigate this?

**Comment by jgoguen** [comment]
You can run calibre with `calibre-debug -g` to get all debug logs from calibre. Do you need the `python{2,3}-configparser` packages though? If you run `sudo dnf remove python{2,3}-configparser` does it want to remove any packages you need? If you remove them does calibre suddenly find `configparser`?

**Comment by srphillips** [comment]
I have been testing this on Calibre 4.8.0 found in the Fedora 31 repos where Python 3 has become the default.  While the plugins install fine for me from the `py3k` branch, there are still some issues with Python 3 compatibility in the Kepub Output plugin and the driver itself that I've found when trying to use it to convert/load books to my device.

Most issues from what I can see are issues with compatibility between `str` and `bytes` and/or character encoding.  I'm only working through a few lines in my spare time, but here's a list of files and line number issues I've found so far:

 * `container.py` - lines 157, 294, 304, 552, 568
 * `conversion/kepub_output.py` - line 121
 * `device/driver.py` - lines 384 and possibly the `cfg.set()` on lines 395-399

This is by no means a comprehensive list, but there might be similar lines in the other files that would need attention as well.  I haven't looked at the Kepub Input plugin or either of the Metadata plugins yet.  There are also a few items like [SafeConfigParser becoming the default ConfigParser](https://docs.python.org/3/whatsnew/3.2.html#configparser) that have changed with Python 3, but I think it still works with the old name for now.

So far, I have forked the repo, but have withheld committing my changes to the above lines for Pull Requests because I'm not sure how you would prefer to handle changes if they also need to be backward compatible with Python 2 for the time being ([six](https://pypi.org/project/six/), [Calibre's polyglot `is_py3` check](https://github.com/kovidgoyal/calibre/blob/master/src/polyglot/builtins.py), etc).  My changes only consider Python 3 at the moment.  Please let me know if you have a preferred method of handling this and I can submit a pull request with what I have.

**Comment by jgoguen** [comment]
Calibre is still Python 2 so all changes must be fully compatible with Python 2 and Python 3 is best effort. I don't know what the plans are for getting calibre up to Python 3 but until the first official Python 3 release package from upstream I have to stay fully Python 2 compatible.

PRs are welcome, but you have to test them on the official upstream calibre package. If something breaks on the official upstream package but not in the Python 3 Fedora package, it has to be fixed even if that breaks the plugin on the distro Python 3 version.

**Comment by jgoguen** [comment]
New versions of the plugins introducing Python 3 compatibility were recently published to MobileRead, IIRC Kovid's scripts poll for new plugins there every hour so calibre should make them available soon. You're looking for version 3.2.2.
