### ISSUE TITLE
Kobo Aura One: Chapter Titles' justification

### ISSUE THREAD

**Issue by sammij** [jgoguen/calibre-kobo-driver#81]
Hi,
on most of the ebooks I converted from epub to kepub, the title text of each and every chapter shows up in my reader as left-justified, despite it showing as center-justified on calibre ebook viewer when used to load either one of the original epub, or the converted kepub straight off the reader's folder.

I tried both Calibre v3.48 on my iMac with system 10.11.6, and v4.60 on my laptop with Win10 - anyhow it doesn't matter, because the .kepub file is interpreted correctly by Calibre View, not when loaded into my Aura One reader.

Please let me know if need any further information, very glad to provide.

Thank you
stefano

**Comment by sammij** [comment]
solved: factory reset.

**Comment by jgoguen** [comment]
Something to consider if this happens again, check your device's justification setting. You can tell the Kobo to override the book setting and always left/centre/right justify text. If I recall correctly, that depends on the style being set in CSS (either a separate file or the `<head>` section) and setting combinations of `text-align` and `text-justify` in an element's `style` attribute will override the device setting. Also, like many things it may only apply to KePub books and this plugin can upload books that fail conversion (as the original ePub). If I recall either of those correctly it would explain why you saw this on most but not all books.

**Comment by sammij** [comment]
Thank you, most appreciated.
