### ISSUE TITLE
Can no longer copy files to Kobo Touch. 

### ISSUE THREAD

**Issue by tomchiverton** [jgoguen/calibre-kobo-driver#82]
This worked fine a few months ago, but now doesn't.

Latest Calibre from the 'wget' install method updated today to version 4.7.0
All plugins updated inside Calibre today.
Reader is a Kobo Touch firmware 4.19.14123 (latest, updated today)

When copying a book a message is displayed :
```
ERROR: Error: Error communicating with device

'NoneType' object has no attribute 'startswith'

Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 90, in run
  File "site-packages/calibre/gui2/device.py", line 594, in _upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 399, in upload_books
  File "site-packages/calibre/devices/kobo/driver.py", line 2099, in upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 313, in _modify_epub
  File "posixpath.py", line 254, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Attached debug log.
[tmps82uVC.txt](https://github.com/jgoguen/calibre-kobo-driver/files/4012798/tmps82uVC.txt)

**Comment by tomchiverton** [comment]
If I disable the extended driver, then everything works as expected

**Comment by Marrin** [comment]
Have the same problem here and disabling the extended driver works for me too.

**Comment by jgoguen** [comment]
I don't have a working Kobo device right now, I can make changes and build a new plugin file as soon as I have a chance but I'll need one of you to test the changes for me.

**Comment by tomchiverton** [comment]
Not a problem. Let me know what needs doing and I'll test.
If you have debugging code you need run, I vaguely know Python :-)
-- 
Tom

**Comment by Marrin** [comment]
Maybe this is already fixed and just needs to be released because the variable that can become `None` in the latest release in June can't become `None` any more since 854308c83dab1afe1807082825d5acbad02093ae.

**Comment by jgoguen** [comment]
Please manually install the plugin ZIP file from https://keybase.pub/jgoguen/calibre-kobo-driver/. I've includes all the plugins so you can update any you have installed.

**Comment by tomchiverton** [comment]
I copied the KoboTouchExtended.zip to /home/falken/.config/calibre/plugins and started Calibre.

Re-enabled the plugin, and tried copying a book - works fine.

I vote to release the new version
