### ISSUE TITLE
Can not sync Collections

### ISSUE THREAD

**Issue by RGWeemhoff** [jgoguen/calibre-kobo-driver#89]
I run on Windows10 Calibre with the extended touch driver  for a Kobo Aura HD, everything up-to-date. 
I did try anything advised to have the Collections in the Calibre library but without success.
[tmpuuflak.txt](https://github.com/jgoguen/calibre-kobo-driver/files/4644299/tmpuuflak.txt)
This debug file is from only connecting the device.

**Comment by jgoguen** [comment]
Collections is a function of the base Kobo driver in calibre, not this plugin, and nothing I see in the log shows any error at all. You need to file a bug against calibre itself at https://launchpad.net/calibre.
