### ISSUE TITLE
Suggestion: Please update the description text in the plugin to include all Kobo devices that work with plugin. Currently the text just has "Kobo Touch, Glo, Mini, Aura HD and Aura firmwares", but doesn't include Forma, Libra.

### ISSUE THREAD

**Issue by hub2git** [jgoguen/calibre-kobo-driver#92]
Dear Joel.
Thanks for your work on the driver.
May I make a suggestion. Please update the description text in the plugin to include all Kobo devices that work with plugin. Currently the text just has "Kobo Touch, Glo, Mini, Aura HD and Aura firmwares", but doesn't include my device, a  Forma, or the latest device, a Libra.  

![Screenshot from 2020-06-09 19-33-10](https://user-images.githubusercontent.com/7141051/84220629-1b637b00-aa88-11ea-9a91-bbec49635de9.png)

**Comment by hub2git** [comment]
https://github.com/jgoguen/calibre-kobo-driver/pull/93

**Comment by jgoguen** [comment]
The description in calibre is separate from anything here in code. I'll reach out to people who may be able to update it, though I would prefer to avoid naming any devices I haven't actually tested with.

**Comment by hub2git** [comment]
Hi Joel. I understand your rationale.
How about listing untested devices then?

**Comment by jgoguen** [comment]
@all-contributors please add @hub2git for content
