### ISSUE TITLE
no __call__ method error converting epub to kepub, Calibre 4.18 x64x Kepub output 3.2.7, Python 3.8.3 x64

### ISSUE THREAD

**Issue by Byte6d65** [jgoguen/calibre-kobo-driver#96]
calibre, version 4.18.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Name Removed)

Convert book 1 of 1 (The Other Side of the Stars)
Conversion options changed from defaults:
  read_metadata_from_opf: u'C:\\Users\\Chan\\AppData\\Local\\Temp\\calibre_y5z9ym\\ydwo2q.opf'
  embed_font_family: u'Verdana'
  output_profile: u'kobo'
  verbose: 2
Resolved conversion options
calibre version: 4.18.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': u'Verdana',
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001A6CD20A408>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'kepub_clean_markup': True,
 'kepub_disable_hyphenation': False,
 'kepub_hyphenate': True,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x000001A6CD21ADC8>,
 'page_breaks_before': u'/',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Chan\\AppData\\Local\\Temp\\calibre_y5z9ym\\ydwo2q.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: EPUB Input running
on C:\Users\Chan\AppData\Local\Temp\calibre_y5z9ym\hkh8gh.epub
Parsing all content...
Parsing OEBPS/file0011.xhtml ...
Parsing OEBPS/title_page.xhtml ...
Parsing OEBPS/file0013.xhtml ...
Parsing OEBPS/file0008.xhtml ...
Parsing OEBPS/file0001.xhtml ...
Parsing OEBPS/file0005.xhtml ...
Parsing OEBPS/file0002.xhtml ...
Parsing OEBPS/file0003.xhtml ...
Parsing OEBPS/file0016.xhtml ...
Parsing OEBPS/file0012.xhtml ...
Parsing OEBPS/file0017.xhtml ...
Parsing OEBPS/file0018.xhtml ...
Parsing OEBPS/file0019.xhtml ...
Parsing OEBPS/file0020.xhtml ...
Parsing OEBPS/file0021.xhtml ...
Parsing OEBPS/file0022.xhtml ...
Parsing OEBPS/file0006.xhtml ...
Parsing OEBPS/file0023.xhtml ...
Parsing OEBPS/file0004.xhtml ...
Parsing OEBPS/file0024.xhtml ...
Parsing OEBPS/file0015.xhtml ...
Parsing OEBPS/file0025.xhtml ...
Parsing OEBPS/file0026.xhtml ...
Parsing OEBPS/file0009.xhtml ...
Parsing OEBPS/file0027.xhtml ...
Parsing OEBPS/file0028.xhtml ...
Parsing OEBPS/file0007.xhtml ...
Parsing OEBPS/file0029.xhtml ...
Parsing OEBPS/file0030.xhtml ...
Parsing OEBPS/file0014.xhtml ...
Parsing OEBPS/stylesheet.css ...
Parsing OEBPS/file0010.xhtml ...
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Embedding font: Verdana
Property: Unknown Property name. [1:37: panose-1]
Property: Unknown Property name. [1:55: panose-1]
Property: Unknown Property name. [1:56: panose-1]
Property: Unknown Property name. [1:74: panose-1]
Source base font size is 12.00000pt
Removing fake margins...
Found 31 items of level: div_2
Found 31 items of level: div_1
div_2  left margin stats: Counter()
div_2  right margin stats: Counter()
div_1  left margin stats: Counter()
div_1  right margin stats: Counter()
Cleaning up manifest...
Trimming unused files from manifest...
Creating KePub Output...
2020-06-14 04:45:12 [DEBUG] Running ePub conversion
Splitting markup on page breaks and flow limits, if any...
	Looking for large trees in OEBPS/file0011.xhtml...
	No large trees found
	Looking for large trees in OEBPS/title_page.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0013.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0008.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0001.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0005.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0002.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0003.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0016.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0012.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0017.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0018.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0019.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0020.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0021.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0022.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0006.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0023.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0004.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0024.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0015.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0025.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0026.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0009.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0027.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0028.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0007.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0029.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0030.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0014.xhtml...
	No large trees found
	Looking for large trees in OEBPS/file0010.xhtml...
	No large trees found
Python function terminated unexpectedly
  Logger instance has no __call__ method (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1275, in run
  File "calibre_plugins.kepubout.conversion.kepub_output", line 107, in convert
  File "site-packages\calibre\ebooks\conversion\plugins\epub_output.py", line 214, in convert
  File "site-packages\calibre\ebooks\oeb\transforms\cover.py", line 85, in __call__
  File "site-packages\calibre\ebooks\oeb\transforms\cover.py", line 137, in insert_cover
  File "site-packages\calibre\ebooks\oeb\transforms\cover.py", line 93, in default_cover
AttributeError: Logger instance has no __call__ method

**Comment by jgoguen** [comment]
@all-contributors please add @Byte6d65 for bug
